// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAutocomplete: typeof import('element-ui/lib/autocomplete')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElEmpty: typeof import('element-ui/lib/empty')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElLink: typeof import('element-ui/lib/link')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    ElTag: typeof import('element-ui/lib/tag')['default']
    KlChannelSearchbar: typeof import('./..')['ChannelSearchbar']
    KlDrawer: typeof import('./..')['Drawer']
    KlLoginForm: typeof import('./..')['LoginForm']
    KlQrcode: typeof import('./..')['Qrcode']
    KlSidebar: typeof import('./..')['Sidebar']
    KlSidebarItem: typeof import('./..')['SidebarItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
